### ISSUE TITLE
WARNING: None Property encountered !

### ISSUE THREAD

**Issue by StukaRT** [JennyKmu/RRO_savefile_editor#1]
WARNING: None Property encountered !
'NoneType' object has no attribute 'name'
Please send the above error to the dev team. Press any key to leave.

While opening this save file:
[slot7.zip](https://github.com/JennyKmu/RRO_savefile_editor/files/7462672/slot7.zip)

**Comment by JennyKmu** [comment]
Thanks for the input, I’ll take a look as soon as I can !

**Comment by JennyKmu** [comment]
Should be solved with the latest release (v0.3.3) !
