### ISSUE TITLE
Rolling Stock: Teleport back to depot

### ISSUE THREAD

**Issue by Leif-The-Head** [JennyKmu/RRO_savefile_editor#20]
Not only Jester in Discord asked for it, I also already thought this was neat.

Proposed functionality:
* "Reset Rolling Stock" Menu
* choose Rolling Stock via a list that shows type, number, name (we have that already) and location.
* set brakes if applicable (handbrakes should be fine, air brakes are influenced by whether it has air anyway)
* set coordinates/rotation to one of a set of coordinates/rotation that are the spawn rails
  * need to be extracted first
  * proximity check to determine which spot is free before placing
  * in case of no free spots: Error

**Comment by JennyKmu** [comment]
Pushed branch 'feature_rs_teleport_depot' for further testing.

**Comment by JennyKmu** [comment]
The ui shows:
Status | Frame type | Frame number | Frame name | [RESPAWN] | [YEET IT]

Status is in red if the car is below 10m in height (probably below map)

[RESPAWN] checks for available spawn points, and teleports the selected frame to the first one available (same order as for buying menu)
[YEET IT] is more reasonable than the previous feature : it teleports and reorients the frames next to the spawn point, at a different place for each frame, but still at a hight position over the ground (to avoid potential elements on the ground). Drop positions should be behind the spawn (where the tracks would go if you continued them past the deck)

**Comment by JennyKmu** [comment]
First in game test :
- Properly detected that spawn points 1 and 2 where occupied
- Properly respawned 3 frames on spawn points 3, 4 and 5, and **the respawned frames were not derailed !**
- Frames respawned were 1 Tier 1 flatcar and 2 tier 2 flat cars

**Comment by JennyKmu** [comment]
Test results:
- [RESPAWN] working properly, tested with all frames, offset for some frame types included.
- [YEET IT] working as intended. Results uncertain if drop zone occupied by something else (trees, other frames, ...)
