### ISSUE TITLE
Cursor overflow

### ISSUE THREAD

**Issue by JennyKmu** [JennyKmu/RRO_savefile_editor#24]
When there is exactly 10 items in a menu, there is some interaction with cursor movement making it possible to go to 11th line (causing an error if trying to edit there)

**Comment by Leif-The-Head** [comment]
Which menu exactly? Or all of them?
I already have an idea why this happens.

**Comment by JennyKmu** [comment]
It happened in the test save you sent me when editing loco/tender contents (since in that menu you get exactly 10 lines, which is the limit for multi-page display. I suspect it will do the same for all menus since they rely on the same structure. The fix isn't too complicated since there's a Boolean which determines whether the lines are split into pages or not. So simply making page-up and page-do to not do anything if that bool is False should solve the issue (haven't had a chance to do it yet)

**Comment by JennyKmu** [comment]
This issue will be corrected along with the reworked terminal user interface.
