### ISSUE TITLE
Not reading save file

### ISSUE THREAD

**Issue by Tenshine1** [JennyKmu/RRO_savefile_editor#41]
Hi All. Im getting the following when I attempt to run 0.38.exe 
file "RRO_savefile_editor|main.py", line 134, in inner_main
file "RRO_savefile_editor|main.py", line 127, in loop
file "RRO_savefile_editor|GVAS\GVAS.py", line 17 in __init__
utf-16-le' codec cant decode bytes in position 38-39: unexpected end of data

attached is my save
[https://drive.google.com/file/d/1wxDO-PsmCZGnoKgSyytiPpA8oeJJvJ_9/view?usp=sharing](url)

(hopes this works, not used github to leave a post before)

**Comment by JennyKmu** [comment]
Thanks, we will look into that

**Comment by Leif-The-Head** [comment]
Closing for now since Rose saw an update, the game saw a couple and this particular problem seemingly didn't return.
