### ISSUE TITLE
RRO_savefile_editor Error 04/11/21 11:26

### ISSUE THREAD

**Issue by razor416** [JennyKmu/RRO_savefile_editor#5]
Hi Jenny, using your script 0.35 to replant the tree's produced the below error.

can only concatenate str (not "WindowsPath") to str

**Comment by JennyKmu** [comment]
Yep, indeed, I was very much tired when I pushed that release. I'm uploading the patch.

**Comment by JennyKmu** [comment]
The hotfix is out : v0.3.5-hotfix-1 #6
