### ISSUE TITLE
'NoneType' object has no 'data' error?

### ISSUE THREAD

**Issue by GamingPlus** [JennyKmu/RRO_savefile_editor#51]
@JennyKmu Or @Leif-The-Head 
i keep getting this error no matter what version of sav editor. Here is a image of when i tried to press enter on players 
[Imgur](https://imgur.com/HzK2qY5)

**Comment by Leif-The-Head** [comment]
After confirming with the save file provided:
Save file comes from physics beta, tried to open it with 0.3.9, which is not compatible.
Use [0.3.10](https://github.com/JennyKmu/RRO_savefile_editor/releases/tag/v0.3.10-beta)
Still works with current build 220127 - so you can safely type "YES" when it asks you to. But it might break again with the next build, I cannot tell in advance 🤷
