### ISSUE TITLE
Nonetype object error

### ISSUE THREAD

**Issue by Mag20KC** [JennyKmu/RRO_savefile_editor#52]
When I select Players I get this error

Select the submenu (press ENTER to confirm):
 - Players
 - Teleport
 - Rolling stock
 - Environment
 - Save & Exit
 - Exit
  File "C:\Users\myuser\AppData\Local\arr\Saved\SaveGames\ROSE_039.pyz\main.py", line 163, in inner_main
'NoneType' object has no attribute 'data'
Please send the above error to the dev team. Press any key to leave.

**Comment by Leif-The-Head** [comment]
The version you're using is not compatible anymore with current save format.
Update to [v0.3.10](https://github.com/JennyKmu/RRO_savefile_editor/releases/tag/v0.3.10-beta)
