### ISSUE TITLE
Unable to access Save-Files

### ISSUE THREAD

**Issue by PiperMp3** [JennyKmu/RRO_savefile_editor#56]
Tested _all_ Rose Versions on the release page with .exes.

.exes older than 039.beta will not detect the save files, but the 3 newest will.
However, all three have the same issue when selecting a save file;

GVASFileFormatError.__init__() missing 1 required positional argument: 'msg'
Please send the above error to the dev team. Press any key to leave.

This happens with ANY save files, either autosaves or custom named save files.

Attaching a save file for troubleshooting
[Firsts - Copy.zip](https://github.com/JennyKmu/RRO_savefile_editor/files/8260966/Firsts.-.Copy.zip)
.

**Comment by Leif-The-Head** [comment]
I do not know where that save file is from, but it most certainly is not Railroads Online.
The error message should be more specific but it is absolutely right to refuse working on this save you attached.
