### ISSUE TITLE
Feature: cars content editor

### ISSUE THREAD

**Issue by dyoung522** [JennyKmu/RRO_savefile_editor#8]
* cars content type can be changed
* cars content amount can be changed
* Should not include tenders and engines
* Current car name should be visible
* Input should be sanitized to meet game values

-v- not on priority for this release -v-
* buttons for filling up a car and emptying up a car
* shortcuts for filling/emptying all cars
* shortcuts for copy/pasting configuration to a different car

Assigned to: @Leif-The-Head

**Comment by Leif-The-Head** [comment]
Push:
* content type can be changed
* if changing to another type, the car will be filled up
* if changing to empty, the car will be emptied
* content amount can be changed
* only for cars that have a content type
* cars are distinguished by their type and each first line of number and name (this is to not clutter the list)
* inputs cannot exceed what is possible ingame

Not done in this version:
* shortcut buttons

Obsolete (as in I don't see a point):
* shortcuts for filling and emptying, as filling can be done by changing to another type then back - plus the shortcut buttons will come at a later date and emptying by switching type to empty

Additional Changes:
* moved everything rolling stock related except the menu itself into its own file
